In [2]:
from sklearn import preprocessing

In [4]:
import numpy as np

In [12]:
original_data = np.random.randint(0, 50000, size=(1,5))
original_data

array([[ 6918, 34691,  8584, 33379, 40956]])

In [14]:
normalized = preprocessing.normalize(original_data)

In [16]:
normalized

array([[0.10782347, 0.54069151, 0.13378963, 0.52024277, 0.63833736]])

In [22]:
xnormalized = np.round(normalized, 2)

In [24]:
xnormalized

array([[0.11, 0.54, 0.13, 0.52, 0.64]])